- hosts: '{{target}}'
  become: yes
  become_method: sudo
  vars_files:
    - environments/{{target}}/vars/all.yml
    - environments/{{target}}/vars/web.yml
    - environments/{{target}}/vars/db.yml
  roles:
    # - server
    - webserver
    # - composer
    # - mariadb

