---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: Add MariaDB-Repository
  become: yes
  become_method: sudo
  apt_repository: repo='deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu trusty main' 

- name: Add Key for MariaDB Repository
  become: yes
  become_method: sudo
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db

- name: Update apt
  become: yes
  become_method: sudo
  apt: update_cache=yes

- name: mariadb | Install MariaDB Packages
  become: yes
  become_method: sudo
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - mariadb-server
    - python-mysqldb

- name: mariadb | Update root password for all root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mariadb.root_password }} login_user=root login_password={{ mariadb.root_password }}
  with_items:
    - "{{ current_hostname.stdout | lower }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: mariadb | Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent login_user=root login_password={{ mariadb.root_password }}
  with_items:
    - localhost
    - "{{ current_hostname.stdout | lower }}"

- name: mariadb | Create databases
  mysql_db: name={{ mariadb.database }} state=present login_user=root login_password={{ mariadb.root_password }}

- name: mariadb | Create users
  mysql_user: name={{ mariadb.user }} password={{ mariadb.password }}  priv=*.*:ALL state=present login_user=root login_password={{ mariadb.root_password }}

#El dato DB
- name: Create database El DATO
  mysql_db: db=eldato state=present login_user='devct' login_password='qwerty'

- name: Copy El Dato (structure) SQL to tmp
  copy: src=eldato.sql dest=/tmp

- name: Import El Dato structure
  mysql_db: name=eldato login_user='devct' login_password='qwerty' state=import target=/tmp/eldato.sql

# phpmyadmin
- name: install phpmyadmin
  apt: name=phpmyadmin state=latest

- name: Add default username and password for MySQL connection.
  lineinfile: >
    dest=/etc/phpmyadmin/config.inc.php
    state=present
    regexp="^.+\['{{ item.key }}'\].+$"
    line="$cfg['Servers'][$i]['{{ item.key }}'] = '{{ item.value }}';"
    insertbefore="^\?>"
  with_items:
  - { key: host, value: "{{ phpmyadmin.host }}" }
  - { key: port, value: "{{ phpmyadmin.port }}" }
  - { key: socket, value: "{{ phpmyadmin.socket }}" }
  - { key: connect_type, value: "{{ phpmyadmin.connect_type }}" }
  - { key: user, value: "{{ phpmyadmin.user }}" }
  - { key: password, value: "{{ phpmyadmin.password }}"}
  - { key: auth_type, value: "{{ phpmyadmin.auth_type }}" }

- name: ensure phpmyadmin installed
  command: ln -s /etc/phpmyadmin/apache.conf /etc/apache2/conf-enabled/phpmyadmin.conf creates=/etc/apache2/conf-enabled/phpmyadmin.conf

- name: ensure phpmyadmin site reloaded
  service: name=apache2 state=restarted
