---
- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install Extra Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: server.packages
  when: server.packages is defined

- name: Configure the timezone
  sudo: yes
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  sudo: yes
  file: src={{server.timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set default system language pack
  shell: locale-gen {{server.locale}}
  sudo: yes

- name: Creates PUB directory
  file: path=/var/www/pub/ state=directory

- name: Adding existing user '{{ user }}' to vboxsf
  user: name='{{ server.user }}' groups=vboxsf append=yes
  when: server.environment  == "development"

- name: ownership and automatically mount in virtualbox via vboxsf
  lineinfile: dest=/etc/rc.local
              insertbefore='exit 0'
              line='mount -t vboxsf -o uid=1000,gid=33,dmode=775 www /var/www'
              state=present
  when: server.environment  == "development"

- name: Install virtualbox-guest-dkms
  sudo: yes
  apt: pkg=virtualbox-guest-dkms state=latest
  when: server.environment  == "development"

# Copy a new interfaces file into /etc/network/interfaces
- copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
    backup: yes
    when: server.environment  == "development"
