---
- name: install apache
  become: yes
  become_method: sudo
  apt: name=apache2 state=present

- name: Install Apache Modules
  apache2_module: state=present name={{ item }}
  with_items: apache.module
  notify: restart apache

- name: install php module for Apache
  become: yes
  become_method: sudo
  apt: name=libapache2-mod-php5 state=present

- name: start Apache
  apt: name=apache2

- name: Install PHP Packages
  sudo: yes
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items: php.packages
  when: php.packages is defined


- name: Disable default apache site
  file:
    path: "/etc/apache2/sites-enabled/000-default"
    state: absent
  notify: Restart apache

- name: Change default apache2.4 site
  become: yes
  become_method: sudo
  template: src=vhost.conf.tpl dest=/etc/apache2/sites-available/000-default.conf
  notify: restart apache

- name: display php errors when not in production
  ini_file: dest=/etc/php5/apache2/php.ini
            section=PHP
            option=display_errors
            value=On
  notify: restart apache

- name: Creates PUB directory
  file: path=/var/www/pub/ state=directory

- name: 4. install Hello World PHP script
  copy: src=index.php dest=/var/www/pub/index.php mode=0664

- name: restart networking
  service: name=networking state=restarted
